### ISSUE TITLE
The README file contains redundant information in the setup instructions

### ISSUE THREAD

**Issue by UmarMohamedUsman** [Azure-Samples/summarization-openai-python-promptflow#16]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Details:**
The document currently outlines the setup options for the development environment in two separate sections. The initial section effectively describes three setup options:

Pre-built environment in the cloud with GitHub Codespaces
Pre-built environment on device with Docker Desktop
Manual setup environment on device with Anaconda or venv

The subsequent paragraph repeats these options, adding unnecessary redundancy:

"To setup the development environment you can leverage either GitHub Codespaces, a local Python environment (using Anaconda or venv), or a VS Code Dev Container environment (using Docker)."

**Suggestion:**
It would enhance the readability and conciseness of the README to remove the latter paragraph, as it does not introduce new information but merely restates the previously mentioned setup options. Consolidating these instructions would prevent user confusion and maintain the documentation's streamlined focus.

**Expected Outcome:**
Simplifying the section to eliminate the redundant paragraph would make the initial guidance on setting up the development environment more direct and clear.

**Comment by cassiebreviu** [comment]
@marlenezw can you look at this documentation issue?

**Comment by marlenezw** [comment]
You're right! Just deleted the section and closing this.
