### ISSUE TITLE
azd up requires azd auth login in GitHub Codespaces

### ISSUE THREAD

**Issue by UmarMohamedUsman** [Azure-Samples/summarization-openai-python-promptflow#17]
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

- Fork the repo
- Open in GitHub Codespaces
- az login
- azd up

### Any log messages given by the failure
> "ERROR: not logged in, run 'azd auth login' to login
![azd-up](https://github.com/Azure-Samples/summarization-openai-python-promptflow/assets/20448629/9f89273c-39df-4868-b6f4-093caa07ad87)

### Expected/desired behavior
> supposed to start the deployment.

Once you run azd auth login, then run azd up the solution starts the deployment. 
It would be good to add 'azd auth login' part of the instructions.

**Comment by cassiebreviu** [comment]
fixed https://github.com/Azure-Samples/summarization-openai-python-promptflow/pull/18
