### ISSUE TITLE
Testing the sample fails

### ISSUE THREAD

**Issue by UmarMohamedUsman** [Azure-Samples/summarization-openai-python-promptflow#20]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Fork the repo
Open in GitHub Codespaces
az login
azd auth login
azd up

In "Step 3: Testing the sample" says:
   pf flow test --flow ./summarizationapp --inputs problem="data/audio-data/issue0.wav"

it fails with the following error message as the summarizationapp doesn't exist in the root. It is under src folder.

### Any log messages given by the failure
![test-failure](https://github.com/Azure-Samples/summarization-openai-python-promptflow/assets/20448629/1d6ba173-45dd-4809-b7ce-18f1d6915e1f)

### Expected/desired behavior
if we run as follows it works.
 pf flow test --flow ./src/summarizationapp --inputs problem="data/audio-data/issue0.wav"

**Comment by marlenezw** [comment]
Your PR I just merged fixes this so closing this issue. Thank you!
