### ISSUE TITLE
push_and_deploy_pf.ipynb file missing

### ISSUE THREAD

**Issue by UmarMohamedUsman** [Azure-Samples/summarization-openai-python-promptflow#22]
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Follow this link
https://github.com/Azure-Samples/summarization-openai-python-promptflow#4-deployment-with-sdk
Under this section it states, "follow the instructions and steps in the notebook push_and_deploy_pf.ipynb under the deployment folder". 
But push_and_deploy_pf.ipynb file is not found under deployment folder.

So not able to deploy the prompt flow to a hosted endpoint on Azure.

**Comment by marlenezw** [comment]
Appreciate the review, adding it in
