### ISSUE TITLE
Test Template

### ISSUE THREAD

**Issue by kristenwomack** [Azure-Samples/summarization-openai-python-promptflow#42]
- [x] Testing works following the Readme, Codespaces is the priority
- [x] Make sure azd works in Codespaces (flag to fix if not)
- [x] We have verification step in README after the resources are deployed, there is a description of what the customer needs to do next
- [x] Ensure managed identity is implemented and working
- [x] If local doesn't work, we need a note in the README (make this explicit)

Nice to have (but document if not working)
- [x] runs local

Must have two testers approval, minimum.

**Comment by marlenezw** [comment]
Hi @kristenwomack, I think this meets all the reuirements on the the AI Studio branch. I just tried testing it on the ACA branch which is currently the default and the speech resource id and region are not being provisioned. I'm testing with Victor to try figure it out. 

So I'd say AI Studio branch is good to go, but not the ACA example yet

**Comment by marlenezw** [comment]
Actually @kristenwomack  I fixed the resources issues and just merged the changes. I've tested this now end to end and it's good to go on main

**Comment by kristenwomack** [comment]
> Actually @kristenwomack I fixed the resources issues and just merged the changes. I've tested this now end to end and it's good to go on main

Sounds good, thank you @marlenezw - we've got it in our PR to included it. cc: @gkulin
